#!/usr/bin/env python3.11
"""Emit appendix F's verbatim instrument sources from the live code.

The paper's appendix F prints the four prompt builders, both detectors, the
severity rule, and the scoring rubric exactly as they run, so a reader can
replay the instrument findings without the repository. Extracting them with
inspect.getsource (rather than pasting) means the appendix cannot drift from
the code; tests/test_appendix_f_fidelity.py asserts the emitted file matches
a fresh extraction.

Writes report/generated/appendix_f_code.tex.
"""
from __future__ import annotations

import inspect
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "report" / "generated" / "appendix_f_code.tex"

sys.path.insert(0, str(REPO_ROOT / "scripts"))

import llm_benchmark as lb  # noqa: E402
import llm_benchmark_common as lbc  # noqa: E402
import qualitative_analysis as qa  # noqa: E402

SECTIONS: list[tuple[str, list]] = [
    (
        "The four prompt strategies (one builder per cycle)",
        [
            lb.build_zero_shot_prompt,
            lb.build_chain_of_thought_prompt,
            lb.build_self_critique_prompt,
            lb.build_constrained_prompt,
        ],
    ),
    (
        "The refusal detector (\\S 7.1); the 40-character rule is the "
        "brevity operationalisation the paper reports",
        [lb.detect_refusal],
    ),
    (
        "The fabrication detector (\\S 7.2): float literals absent from "
        "context, citations without a matching title 3-gram",
        [lb.known_metric_values, lb.detect_hallucinations],
    ),
    (
        "The severity rule (\\S 7.4); the CRITICAL boundary is "
        "0.8 x 0.9 = 0.72, constructed here, with no external provenance",
        [qa.classify_severity],
    ),
    (
        "The scoring rubric (\\S 7.5): weights 40/20/15/15/10; note "
        "cause-alignment's flat 10.0 when the baseline lists no cause labels "
        "-- the default that scored four empty responses",
        [
            lbc.score_llm_output,
            lbc._score_completeness,
            lbc._score_severity,
            lbc._score_cause_alignment,
            lbc._score_mitigation_specificity,
            lbc._score_research_grounding,
        ],
    ),
]


WRAP_COLUMN = 64  # what a \scriptsize tt column fits; longer lines bleed


def _wrap(src: str) -> str:
    """Hard-wrap long lines with a visible continuation marker so the
    verbatim stays inside its column. Byte-exact sources live in the repo."""
    out = []
    for line in src.split("\n"):
        while len(line) > WRAP_COLUMN:
            out.append(line[:WRAP_COLUMN] + "\\")
            line = "    " + line[WRAP_COLUMN:]
        out.append(line)
    return "\n".join(out)


def render() -> str:
    parts = [
        "% Generated by scripts/emit_appendix_f.py -- do not edit.\n"
        "% Sources extracted from the live modules with inspect.getsource;\n"
        "% tests/test_artifact_map.py keeps this file in sync.\n"
        "\\noindent\\emph{Lines longer than "
        f"{WRAP_COLUMN}"
        " columns are wrapped with a trailing backslash for typesetting; "
        "the repository holds the byte-exact sources.}\n"
    ]
    for heading, functions in SECTIONS:
        parts.append(f"\\subsection*{{{heading}}}\n")
        for fn in functions:
            module = fn.__module__.replace("_", "\\_")
            src = _wrap(inspect.getsource(fn).rstrip())
            parts.append(
                f"\\noindent\\texttt{{scripts/{module}.py}}\n"
                "{\\scriptsize\\begin{verbatim}\n"
                f"{src}\n"
                "\\end{verbatim}}\n"
            )
    return "\n".join(parts)


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
